#!/bin/bash
if [ "$1" = "" ]; then
  exit 1
fi

for i in $*; do
  oldfile=$i
  newfile=`echo $i | tr "[:upper:]" "[:lower:]"`
  if [ "$newfile" != "$oldfile" ]; then
    echo "$oldfile -> $newfile"
    mv $oldfile $newfile
  fi
done
