#!/bin/bash

width=800
height=600
aprofile=`locate AdobeRGB1998.icc|head -1`
sprofile=`locate sRGB.icc|head -1`

if [ "$1" != "" ]; then
  width=$1
fi

if [ "$2" != "" ]; then
  height=$2
fi

shift 2

ls -1 $@|while read img; do
  ext=`echo $img | awk -F'.' '{print $NF}'`
  bn=`echo $img | awk -F'/' '{print $NF}' | sed "s/\.\${ext}$//g"`
  w=`exiftool -T -ImageWidth "$img"` 
  h=`exiftool -T -ImageHeight "$img"` 
  cp=`exiftool -T -ColorSpace "$img"` 
  emb=`exiftool -T -ProfileCMMType "$img"`
  echo -n "Converting $img... "
  if [ $w -gt $h ]; then
    if [ "$emb" != "-" ]; then
      convert "$img" -profile "$sprofile" -resize ${width}x -quality 90 "/tmp/${bn}_$$.${ext}"
    else
      if [ "$cp" == "Adobe RGB" ]; then
        convert "$img" -profile "$aprofile" -profile "$sprofile" -resize ${width}x -quality 90 "/tmp/${bn}_$$.${ext}"
      else
        convert "$img" -resize ${width}x -quality 90 "/tmp/${bn}_$$.${ext}"
      fi
    fi
  else
    if [ "$emb" != "-" ]; then
      convert "$img" -profile "$sprofile" -resize x${height} -quality 90 "/tmp/${bn}_$$.${ext}"
    else
      if [ "$cp" == "Adobe RGB" ]; then
        convert "$img" -profile "$aprofile" -profile "$sprofile" -resize x${height} -quality 90 "/tmp/${bn}_$$.${ext}"
      else
        convert "$img" -resize x${height} -quality 90 "/tmp/${bn}_$$.${ext}"
      fi
    fi
  fi
  exiftool -ColorSpace="sRGB" "/tmp/${bn}_$$.${ext}"
  mkdir -p "${width}x${height}"
  cp "/tmp/${bn}_$$.${ext}" "${width}x${height}/${bn}_s.${ext}"
  rm -f /tmp/${bn}_$$.${ext}
  echo "Done!"
done

